<?php

return [
    'enabled' => (bool) env('TRUTHSHIELD_BOT_PROTECTION_ENABLED', env('APP_ENV') === 'production'),
    'turnstile_enabled' => (bool) env('TRUTHSHIELD_TURNSTILE_ENABLED', false),
    'turnstile_site_key' => env('TRUTHSHIELD_TURNSTILE_SITE_KEY'),
    'turnstile_secret' => env('TRUTHSHIELD_TURNSTILE_SECRET'),
    'turnstile_verify_url' => env('TRUTHSHIELD_TURNSTILE_VERIFY_URL', 'https://challenges.cloudflare.com/turnstile/v0/siteverify'),
    'challenge_mode' => env('TRUTHSHIELD_BOT_CHALLENGE_MODE', 'always'),
    'quick_action_read_gate_enabled' => (bool) env('TRUTHSHIELD_QUICK_ACTION_READ_GATE_ENABLED', false),
    'quick_action_bar_enabled' => (bool) env('TRUTHSHIELD_QUICK_ACTION_BAR_ENABLED', false),
    'challenge_threshold' => (int) env('TRUTHSHIELD_BOT_CHALLENGE_THRESHOLD', 50),
    'block_threshold' => (int) env('TRUTHSHIELD_BOT_BLOCK_THRESHOLD', 90),
    'expected_hostname' => env('TRUTHSHIELD_TURNSTILE_HOSTNAME', parse_url(env('FRONTEND_URL', ''), PHP_URL_HOST)),
    'fallback_per_minute' => (int) env('TRUTHSHIELD_BOT_FALLBACK_PER_MINUTE', 3),
    'fallback_per_hour' => (int) env('TRUTHSHIELD_BOT_FALLBACK_PER_HOUR', 30),
    'trust_failure_window_minutes' => 10,
    'trust_failure_step' => 5,
    'trust_failure_delta' => 0.05,
    'trust_failure_daily_max' => 0.20,
    'trust_recovery_days' => 30,
    'challenge_actions' => [
        'auth.dev_login',
        'auth.oauth_callback',
        'vote.create',
        'reader.reaction',
        'evidence.react',
        'evidence.report',
        'community.signal',
        'domain.report',
        'url.classification',
        'trusted_source.suggest',
        'data_request.create',
    ],
    'blocked_user_agent_patterns' => [
        'curl',
        'python-requests',
        'scrapy',
        'httpclient',
        'headlesschrome',
        'phantomjs',
    ],
    'extension_nonce_ttl_seconds' => (int) env('TRUTHSHIELD_EXTENSION_NONCE_TTL_SECONDS', 300),
];
