<?php

namespace App\Support;

use Illuminate\Support\Str;

class AdminChineseLabels
{
    /**
     * Chinese labels shared by Filament forms and tables.
     *
     * @var array<string, string>
     */
    private const FIELD_LABELS = [
        'action' => '操作',
        'action_url' => '操作連結',
        'activated_at' => '啟用時間',
        'abuse_multiplier' => '濫用風險倍率',
        'algorithm_version' => '演算法版本',
        'article_selector' => '文章選擇器',
        'auth_provider' => '登入來源',
        'blocked_path_pattern' => '封鎖路徑規則',
        'body' => '內容',
        'check_type' => '檢查類型',
        'checked_at' => '檢查時間',
        'color' => '顏色',
        'content_selector' => '內文選擇器',
        'created_at' => '建立時間',
        'decay_seconds' => '衰退秒數',
        'delta' => '分數變動',
        'description' => '描述',
        'details' => '細節',
        'display_name' => '顯示名稱',
        'domain' => '網域',
        'edge_type' => '關聯類型',
        'email' => '電子郵件',
        'email_verified_at' => '信箱驗證時間',
        'event_type' => '事件類型',
        'evidence_host' => '證據網域',
        'evidence_note' => '證據說明',
        'evidence_safety' => '證據安全性',
        'evidence_type' => '證據類型',
        'evidence_url' => '證據連結',
        'expires_at' => '到期時間',
        'fb_id' => 'Facebook ID',
        'final_evidence_payload' => '定案證據快照',
        'final_status_payload' => '定案狀態快照',
        'finalized_at' => '定案時間',
        'hash' => 'URL 指紋',
        'helpful' => '有幫助',
        'host' => '來源網域',
        'identity_level' => '身份等級',
        'identity_multiplier' => '身份倍率',
        'ip_address' => 'IP 位址',
        'is_active' => '啟用',
        'is_admin' => '後台權限',
        'key' => '設定鍵',
        'last_reported_at' => '最後回報時間',
        'last_used_at' => '最後使用時間',
        'low_trust_multiplier' => '低信任倍率',
        'max_attempts' => '最大次數',
        'metadata' => '中繼資料',
        'name' => '名稱',
        'new_score' => '新信任分數',
        'news_url_id' => '新聞',
        'normalized_url' => '正規化 URL',
        'note' => '備註',
        'notes' => '備註',
        'original_url' => '原始 URL',
        'page_title' => '頁面標題',
        'password' => '密碼',
        'previous_score' => '原信任分數',
        'priority' => '優先序',
        'provider' => '登入提供者',
        'provider_user_id' => '提供者使用者 ID',
        'public_reason' => '公開原因',
        'quality_score' => '證據品質分',
        'read_at' => '已讀時間',
        'reason' => '原因',
        'report_count' => '回報數',
        'review_note' => '審核備註',
        'reviewed' => '已審核',
        'risk_status' => '風險狀態',
        'scope' => '範圍',
        'score' => '分數',
        'selector' => '選擇器',
        'severity' => '嚴重度',
        'signal_hash' => '訊號雜湊',
        'signal_type' => '訊號類型',
        'slug' => '代稱',
        'snapshot_status' => '快照狀態',
        'source' => '來源',
        'source_type' => '來源類型',
        'source_user_id' => '來源使用者',
        'status' => '狀態',
        'subject_id' => '目標 ID',
        'subject_type' => '目標類型',
        'summary' => '摘要',
        'tag_id' => '標籤',
        'target_user_id' => '目標使用者',
        'title' => '標題',
        'title_selector' => '標題選擇器',
        'title_snapshot' => '標題快照',
        'trust_bonus' => '信任加成',
        'trust_score' => '信任分數',
        'type' => '類型',
        'updated_at' => '更新時間',
        'url' => '網址',
        'used_at' => '使用時間',
        'user_id' => '使用者',
        'version' => '版本',
        'vote_id' => '投票',
        'votes_count' => '投票數',
        'voting_closes_at' => '投票截止時間',
        'weight_score' => '加權分數',
    ];

    public static function field(string $name): string
    {
        $key = Str::of($name)->afterLast('.')->snake()->toString();

        return self::FIELD_LABELS[$key] ?? Str::of($key)->replace('_', ' ')->title()->toString();
    }
}
